var AudioManager=(function(){var USE_FILES=false;var ctx=null;var musicOn=true;var sfxOn=true;var masterGain=null;var musicGain=null;var sfxGain=null;var bgmRunning=false;var bgmTimer=null;function init(){}
function _ensureCtx(){if(ctx){if(ctx.state==='suspended')ctx.resume();return true;}
try{ctx=new(window.AudioContext||window.webkitAudioContext)();masterGain=ctx.createGain();masterGain.gain.value=0.5;masterGain.connect(ctx.destination);musicGain=ctx.createGain();musicGain.gain.value=0.12;musicGain.connect(masterGain);sfxGain=ctx.createGain();sfxGain.gain.value=0.35;sfxGain.connect(masterGain);return true;}catch(e){ctx=null;return false;}}
function resumeContext(){_ensureCtx();}
function playNote(freq,duration,startTime,type,gainNode){if(!_ensureCtx())return;type=type||'sine';gainNode=gainNode||sfxGain;var osc=ctx.createOscillator();var gain=ctx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(0.3,startTime);gain.gain.exponentialRampToValueAtTime(0.001,startTime+duration);osc.connect(gain);gain.connect(gainNode);osc.start(startTime);osc.stop(startTime+duration);}
function playCorrect(){if(!sfxOn)return;var now=ctx.currentTime;var notes=[523,659,784,1047];for(var i=0;i<notes.length;i++){playNote(notes[i],0.12,now+i*0.08,'sine');}}
function playWrong(){if(!sfxOn)return;var now=ctx.currentTime;var osc=ctx.createOscillator();var gain=ctx.createGain();osc.type='triangle';osc.frequency.setValueAtTime(350,now);osc.frequency.linearRampToValueAtTime(150,now+0.35);gain.gain.setValueAtTime(0.2,now);gain.gain.exponentialRampToValueAtTime(0.001,now+0.4);osc.connect(gain);gain.connect(sfxGain);osc.start(now);osc.stop(now+0.45);}
function playClick(){if(!sfxOn)return;playNote(660,0.06,ctx.currentTime,'sine');}
function playPickup(){if(!sfxOn)return;playNote(520,0.08,ctx.currentTime,'triangle');}
function playStar(index){if(!sfxOn)return;var notes=[523,659,784];playNote(notes[index]||784,0.25,ctx.currentTime,'sine');}
function playLevelComplete(){if(!sfxOn)return;var now=ctx.currentTime;var notes=[523,587,659,784,1047];for(var i=0;i<notes.length;i++){playNote(notes[i],0.28,now+i*0.13,'triangle');}}
function playAnimalSound(animalId){if(!sfxOn)return;var animal=ANIMALS[animalId];if(!animal||!animal.songNotes)return;var now=ctx.currentTime;for(var i=0;i<animal.songNotes.length;i++){playNote(animal.songNotes[i],0.15,now+i*0.1,'triangle');}}
function startBGM(){if(!musicOn)return;if(!_ensureCtx())return;stopBGM();bgmRunning=true;_playBGMLoop();}
function _playBGMLoop(){if(!bgmRunning||!musicOn||!_ensureCtx())return;var now=ctx.currentTime;var melody=[262,262,392,392,440,440,392,0,349,349,330,330,294,294,262,0,392,392,349,349,330,330,294,0,392,392,349,349,330,330,294,0,262,262,392,392,440,440,392,0,349,349,330,330,294,294,262,0,];var noteDur=0.32;for(var i=0;i<melody.length;i++){if(melody[i]>0){playNote(melody[i],0.22,now+i*noteDur,'triangle',musicGain);}}
var totalMs=melody.length*noteDur*1000;bgmTimer=setTimeout(_playBGMLoop,totalMs);}
function stopBGM(){bgmRunning=false;if(bgmTimer){clearTimeout(bgmTimer);bgmTimer=null;}}
function toggleMusic(){musicOn=!musicOn;if(musicOn){startBGM();}else{stopBGM();}
return musicOn;}
function toggleSfx(){sfxOn=!sfxOn;return sfxOn;}
function setMusic(on){musicOn=on;}
function setSfx(on){sfxOn=on;}
var spriteBuffer=null;var spriteManifest=null;var spriteLoaded=false;var spriteLoading=false;var WORD_ID_MAP={cow:'calf',sheep:'lamb',horse:'pony',};function loadAnimalSprite(){if(spriteLoaded||spriteLoading)return;spriteLoading=true;var wavUrl='assets/audio/animals.wav';var jsonUrl='assets/audio/animals.json';fetch(wavUrl).then(function(res){if(!res.ok)throw new Error('WAV load failed');return res.arrayBuffer();}).then(function(buf){if(!_ensureCtx())return Promise.reject('No AudioContext');return ctx.decodeAudioData(buf);}).then(function(audioBuf){spriteBuffer=audioBuf;return fetch(jsonUrl).then(function(r){return r.json();});}).then(function(manifest){spriteManifest=manifest;spriteLoaded=true;spriteLoading=false;}).catch(function(e){spriteLoading=false;console.warn('加载动物音频雪碧图失败:',e);});}
function playAnimalWord(animalId){if(!spriteLoaded){loadAnimalSprite();return;}
if(!_ensureCtx()||!spriteBuffer||!spriteManifest)return;var segId=WORD_ID_MAP[animalId]||animalId;var seg=spriteManifest.segments[segId];if(!seg)return;var gain=ctx.createGain();gain.gain.value=0.5;gain.connect(masterGain||ctx.destination);var source=ctx.createBufferSource();source.buffer=spriteBuffer;source.connect(gain);source.start(0,seg.start,seg.duration);}
var praiseBuffer=null;var praiseManifest=null;var praiseLoaded=false;var praiseLoading=false;function loadPraiseSprite(){if(praiseLoaded||praiseLoading)return;praiseLoading=true;var wavUrl='assets/audio/praise.wav';var jsonUrl='assets/audio/praise.json';fetch(wavUrl).then(function(res){if(!res.ok)throw new Error('Praise WAV load failed');return res.arrayBuffer();}).then(function(buf){if(!_ensureCtx())return Promise.reject('No AudioContext');return ctx.decodeAudioData(buf);}).then(function(audioBuf){praiseBuffer=audioBuf;return fetch(jsonUrl).then(function(r){return r.json();});}).then(function(manifest){praiseManifest=manifest;praiseLoaded=true;praiseLoading=false;}).catch(function(e){praiseLoading=false;console.warn('加载鼓励语音雪碧图失败:',e);});}
function playPraise(segId){if(!praiseLoaded){loadPraiseSprite();return;}
if(!ctx||!praiseBuffer||!praiseManifest)return;var seg=praiseManifest.segments[segId];if(!seg)return;var gain=ctx.createGain();gain.gain.value=0.45;gain.connect(masterGain||ctx.destination);var source=ctx.createBufferSource();source.buffer=praiseBuffer;source.connect(gain);source.start(0,seg.start,seg.duration);}
return{init:init,resumeContext:resumeContext,playCorrect:playCorrect,playWrong:playWrong,playClick:playClick,playPickup:playPickup,playStar:playStar,playLevelComplete:playLevelComplete,playAnimalSound:playAnimalSound,startBGM:startBGM,stopBGM:stopBGM,toggleMusic:toggleMusic,toggleSfx:toggleSfx,setMusic:setMusic,setSfx:setSfx,isMusicOn:function(){return musicOn;},isSfxOn:function(){return sfxOn;},loadAnimalSprite:loadAnimalSprite,playAnimalWord:playAnimalWord,loadPraiseSprite:loadPraiseSprite,playPraise:playPraise,};})();