var GameUI=(function(){var gameApp,animalDisplay,animalNameLabel,foodTray,progressDots;var scoreValueEl,comboValueEl,floatScoreEl,floatHeartEl,encourageText;var dropIndicator,dragLayer,animalZone,starsDisplay;var levelCompleteOverlay;var draggedFoodClone=null,draggedOriginal=null,dragStartRect=null,dragActive=false;var hopTimer=null;var currentLevelData=null;var inputLocked=false;function post(type,data){window.parent.postMessage({type:type,data:data||{}},'*');}
function initElements(){gameApp=document.getElementById('game-app');animalDisplay=document.getElementById('animal-display');animalNameLabel=document.getElementById('animal-name-label');foodTray=document.getElementById('food-tray');progressDots=document.getElementById('progress-dots');scoreValueEl=document.getElementById('score-value');comboValueEl=document.getElementById('combo-value');floatScoreEl=document.getElementById('float-score');floatHeartEl=document.getElementById('float-heart');encourageText=document.getElementById('encourage-text');dropIndicator=document.getElementById('drop-indicator');dragLayer=document.getElementById('drag-layer');animalZone=document.getElementById('animal-zone');starsDisplay=document.getElementById('stars-display');levelCompleteOverlay=document.getElementById('level-complete-overlay');}
function renderGame(levelData){inputLocked=false;currentLevelData=levelData;var animal=ANIMALS[levelData.animalId];animalDisplay.innerHTML='<span class="animal-emoji idle">'+animal.emoji+'</span>';animalNameLabel.innerHTML='<span class="animal-cn">'+animal.name+'</span><span class="animal-en">'+animal.en+'</span>';_renderFoodTray();_renderProgress();updateScore();encourageText.textContent='';encourageText.classList.remove('show');_scheduleHop();_showGuideBubble();}
function _renderFoodTray(){foodTray.innerHTML='';var f=GameManager.getFoodOptions();for(var i=0;i<f.length;i++){var fd=FOODS[f[i]];if(!fd)continue;var item=document.createElement('div');item.className='food-item'+(GameManager.isFoodExhausted(fd.id)?' exhausted':'');item.setAttribute('data-food-id',fd.id);item.innerHTML='<span class="food-emoji">'+fd.emoji+'</span><span class="food-name-cn">'+fd.name+'</span><span class="food-name-en">'+fd.en+'</span>';foodTray.appendChild(item);}}
function _renderProgress(){progressDots.innerHTML='';var t=GameManager.getTargetCount();var c=GameManager.getCorrectCount();for(var i=0;i<t;i++){var d=document.createElement('span');d.className='progress-dot'+(i<c?' filled':'');d.textContent=i<c?'💗':'🤍';progressDots.appendChild(d);}}
function updateScore(){scoreValueEl.textContent=GameManager.getScore();comboValueEl.textContent=GameManager.getCombo();}
function setupDrag(){foodTray.addEventListener('pointerdown',_onPointerDown);document.addEventListener('pointermove',_onPointerMove);document.addEventListener('pointerup',_onPointerUp);document.addEventListener('pointercancel',_onPointerUp);foodTray.addEventListener('contextmenu',function(e){e.preventDefault();});animalZone.addEventListener('pointerdown',_onAnimalTap);}
function _onPointerDown(e){if(inputLocked)return;var t=e.target.closest('.food-item');if(!t||t.classList.contains('being-dragged')||t.classList.contains('exhausted'))return;e.preventDefault();post('audio',{method:'playPickup'});dragStartRect=t.getBoundingClientRect();draggedOriginal=t;t.classList.add('being-dragged');var c=t.cloneNode(true);c.className='drag-clone active';c.style.left=dragStartRect.left+'px';c.style.top=dragStartRect.top+'px';c.style.width=dragStartRect.width+'px';c.style.height=dragStartRect.height+'px';dragLayer.appendChild(c);draggedFoodClone=c;dragActive=true;t.setPointerCapture(e.pointerId);_updateClonePos(e.clientX,e.clientY);_checkDropHover(e.clientX,e.clientY);}
function _onPointerMove(e){if(!dragActive||!draggedFoodClone)return;e.preventDefault();_updateClonePos(e.clientX,e.clientY);_checkDropHover(e.clientX,e.clientY);}
function _updateClonePos(cx,cy){if(!draggedFoodClone)return;var w=draggedFoodClone.offsetWidth,h=draggedFoodClone.offsetHeight;draggedFoodClone.style.left=(cx-w/2)+'px';draggedFoodClone.style.top=(cy-h/2-GAME_CONFIG.FOOD_DRAG_OFFSET_Y)+'px';}
function _checkDropHover(cx,cy){if(!animalZone)return;var r=animalZone.getBoundingClientRect();var mx=r.left+r.width/2,my=r.top+r.height/2;var inZ=Math.sqrt((cx-mx)*(cx-mx)+(cy-my)*(cy-my))<=GAME_CONFIG.DROP_ZONE_RADIUS;dropIndicator.classList.toggle('highlight',inZ);var em=animalDisplay.querySelector('.animal-emoji');if(em)em.classList.toggle('excited',inZ);}
function _onPointerUp(e){if(!dragActive)return;dragActive=false;var fid=draggedOriginal?draggedOriginal.getAttribute('data-food-id'):null;var ce=draggedFoodClone,oe=draggedOriginal,or=dragStartRect;draggedFoodClone=null;draggedOriginal=null;dragStartRect=null;dropIndicator.classList.remove('highlight');var em=animalDisplay.querySelector('.animal-emoji');if(em)em.classList.remove('excited');if(oe){try{oe.releasePointerCapture(e.pointerId);}catch(ex){}}
if(!fid||!ce)return;var inZ=false;if(animalZone){var r=animalZone.getBoundingClientRect();var mx=r.left+r.width/2,my=r.top+r.height/2;inZ=Math.sqrt((e.clientX-mx)*(e.clientX-mx)+(e.clientY-my)*(e.clientY-my))<=GAME_CONFIG.DROP_ZONE_RADIUS;}
if(inZ){var res=GameManager.handleDrop(fid);if(res&&res.result==='correct')_playCorrect(ce,oe,res);else if(res&&res.result==='wrong')_playWrong(ce,oe,or);else _returnFood(ce,oe,or);}
else{GameManager.handleDropOutside();_returnFood(ce,oe,or);}}
function _playCorrect(ce,oe,res){inputLocked=true;post('audio',{method:'playCorrect'});post('audio',{method:'playAnimalSound',animalId:res.animalId});post('audio',{method:'playPraise',id:'praise'});var rr=animalZone.getBoundingClientRect();ce.style.transition='all .35s ease-in';ce.style.transform='scale(.1)';ce.style.left=(rr.left+rr.width/2)+'px';ce.style.top=(rr.top+rr.height/2)+'px';ce.style.opacity='0';_showFloatHeart();_showFloatScore('+'+res.bonus);_animateAnimalHappy();if(res.encourage){encourageText.textContent=res.encourage;encourageText.classList.add('show');setTimeout(function(){encourageText.classList.remove('show');},1800);}
updateScore();_renderProgress();setTimeout(function(){if(ce.parentNode)ce.parentNode.removeChild(ce);if(oe){oe.classList.add('food-pop-back');oe.classList.remove('being-dragged');var fid=oe.getAttribute('data-food-id');if(fid&&GameManager.isFoodExhausted(fid))oe.classList.add('exhausted');setTimeout(function(){oe.classList.remove('food-pop-back');},400);}inputLocked=false;if(GameManager.isLevelComplete())_triggerLevelComplete();},400);}
function _playWrong(ce,oe,or){inputLocked=true;post('audio',{method:'playWrong'});post('audio',{method:'playPraise',id:'retry'});var em=animalDisplay.querySelector('.animal-emoji');if(em){em.classList.add('shake');setTimeout(function(){em.classList.remove('shake');},500);}
var av=document.getElementById('game-avatar');if(av){av.classList.add('shake');setTimeout(function(){av.classList.remove('shake');},500);}
ce.style.backgroundColor='rgba(255,0,0,.15)';updateScore();_animFoodBack(ce,oe,or);}
function _returnFood(ce,oe,or){inputLocked=true;updateScore();_animFoodBack(ce,oe,or);}
function _animFoodBack(ce,oe,or){if(!or){if(ce.parentNode)ce.parentNode.removeChild(ce);if(oe)oe.classList.remove('being-dragged');inputLocked=false;return;}
ce.style.transition='all .4s cubic-bezier(.175,.885,.32,1.275)';ce.style.left=or.left+'px';ce.style.top=or.top+'px';ce.style.width=or.width+'px';ce.style.height=or.height+'px';ce.style.transform='scale(1)';ce.style.opacity='.8';setTimeout(function(){if(ce.parentNode)ce.parentNode.removeChild(ce);if(oe){oe.classList.add('food-pop-back');oe.classList.remove('being-dragged');setTimeout(function(){oe.classList.remove('food-pop-back');},400);}inputLocked=false;},450);}
function _animateAnimalHappy(){var em=animalDisplay.querySelector('.animal-emoji');if(em){em.classList.add('happy');setTimeout(function(){em.classList.remove('happy');},500);}var av=document.getElementById('game-avatar');if(av){av.classList.add('happy');setTimeout(function(){av.classList.remove('happy');},500);}}
function _onAnimalTap(e){if(inputLocked||e.target.closest('.food-item'))return;var ld=GameManager.getCurrentLevelData();if(!ld)return;post('audio',{method:'playAnimalWord',animalId:ld.animalId});var em=animalDisplay.querySelector('.animal-emoji');if(em){em.classList.add('hop');setTimeout(function(){if(em)em.classList.remove('hop');},700);}
_showAnimalReaction();var av=document.getElementById('game-avatar');if(av){av.classList.add('blink');setTimeout(function(){if(av)av.classList.remove('blink');},400);}}
function _showFloatHeart(){var r=animalZone.getBoundingClientRect();floatHeartEl.style.left=(r.left+r.width/2-25)+'px';floatHeartEl.style.top=r.top+'px';floatHeartEl.classList.remove('show');void floatHeartEl.offsetWidth;floatHeartEl.classList.add('show');}
function _showFloatScore(txt){var r=animalZone.getBoundingClientRect();floatScoreEl.textContent=txt;floatScoreEl.style.left=(r.left+r.width/2-30)+'px';floatScoreEl.style.top=(r.top-20)+'px';floatScoreEl.classList.remove('show');void floatScoreEl.offsetWidth;floatScoreEl.classList.add('show');}
function _showAnimalReaction(){var r=animalZone.getBoundingClientRect();var el=document.createElement('div');el.className='animal-reaction';el.textContent='😊';el.style.left=(r.left+r.width/2-20)+'px';el.style.top=(r.top+20)+'px';document.body.appendChild(el);setTimeout(function(){if(el.parentNode)el.parentNode.removeChild(el);},1200);}
function _triggerLevelComplete(){inputLocked=true;var res=GameManager.completeLevel();_spawnConfetti();var photo=document.getElementById('celebrate-photo');if(photo){photo.src='assets/images/celebrate-'+(Math.floor(Math.random()*3)+1)+'.jpg';photo.classList.remove('pop-in');void photo.offsetWidth;photo.classList.add('pop-in');}
levelCompleteOverlay.classList.add('active');document.getElementById('final-score').textContent=res.score;var ses=starsDisplay.querySelectorAll('.star');for(var i=0;i<ses.length;i++){ses[i].classList.remove('lit');ses[i].textContent='⭐';}
setTimeout(function(){post('audio',{method:'playLevelComplete'});post('audio',{method:'playPraise',id:'praise'});_lightStars(0,res.stars,ses);},500);}
function _lightStars(idx,total,ses){if(idx>=total)return;setTimeout(function(){ses[idx].classList.add('lit');ses[idx].textContent='🌟';post('audio',{method:'playStar',index:idx});_lightStars(idx+1,total,ses);},500);}
function _spawnConfetti(){var c=document.getElementById('confetti-container');if(!c)return;c.innerHTML='';var cols=['#ff6b6b','#ffd93d','#6bcb77','#4d96ff','#ff9f43','#ee5a89','#a55eea','#2ed573'];for(var i=0;i<60;i++){var p=document.createElement('div');p.className='confetti-piece';p.style.left=Math.random()*100+'%';p.style.backgroundColor=cols[Math.floor(Math.random()*cols.length)];p.style.animationDelay=Math.random()*1.5+'s';p.style.animationDuration=(2+Math.random()*3)+'s';p.style.width=(6+Math.random()*10)+'px';p.style.height=(6+Math.random()*14)+'px';p.style.borderRadius=Math.random()>.5?'50%':'2px';c.appendChild(p);}setTimeout(function(){c.innerHTML='';},4000);}
function _showGuideBubble(){var b=document.getElementById('guide-bubble');if(!b)return;b.classList.remove('hide');b.classList.add('show');post('audio',{method:'playPraise',id:'hello'});setTimeout(function(){b.classList.remove('show');b.classList.add('hide');},2500);}
function _scheduleHop(){_clearHopTimer();function next(){hopTimer=setTimeout(function(){var em=animalDisplay.querySelector('.animal-emoji');if(em&&em.classList.contains('idle')){em.classList.add('hop');post('audio',{method:'playAnimalSound',animalId:GameManager.getCurrentLevelData().animalId});setTimeout(function(){if(em)em.classList.remove('hop');},700);}if(GameManager.getState()!=='menu')next();},4000+Math.random()*4000);}next();}
function _clearHopTimer(){if(hopTimer){clearTimeout(hopTimer);hopTimer=null;}}
function hideLevelComplete(){levelCompleteOverlay.classList.remove('active');}
function cleanupGame(){_clearHopTimer();}
return{initElements:initElements,renderGame:renderGame,updateScore:updateScore,setupDrag:setupDrag,hideLevelComplete:hideLevelComplete,cleanupGame:cleanupGame};})();