(function(){UIManager.initElements();AudioManager.init();var settings=StorageManager.getSettings();AudioManager.setMusic(settings.music);AudioManager.setSfx(settings.sfx);function onLevelClick(levelId){UIManager.showGame();AudioManager.stopBGM();var gameReady=false;function trySend(){var iframe=document.getElementById('game-iframe');iframe.contentWindow.postMessage({type:'start-level',levelId:levelId},'*');}
trySend();setTimeout(function(){trySend();},200);setTimeout(function(){trySend();},500);}
function onOpenSettings(){UIManager.showSettings();}
var audioProxy={playCorrect:function(){AudioManager.playCorrect();},playWrong:function(){AudioManager.playWrong();},playPickup:function(){AudioManager.playPickup();},playLevelComplete:function(){AudioManager.playLevelComplete();},playAnimalSound:function(d){AudioManager.playAnimalSound(d.animalId);},playAnimalWord:function(d){AudioManager.loadAnimalSprite();AudioManager.playAnimalWord(d.animalId);},playPraise:function(d){AudioManager.loadPraiseSprite();AudioManager.playPraise(d.id);},playStar:function(d){AudioManager.playStar(d.index);},};window.addEventListener('message',function(e){var msg=e.data;if(!msg||!msg.type)return;if(msg.type==='audio'){AudioManager.resumeContext();var fn=audioProxy[msg.data.method];if(fn)fn(msg.data);}else if(msg.type==='nav'&&msg.data&&msg.data.target==='menu'){UIManager.showMenu();UIManager.renderMenu();if(AudioManager.isMusicOn())AudioManager.startBGM();}else if(msg.type==='music-on'){AudioManager.setMusic(true);AudioManager.startBGM();}
else if(msg.type==='music-off'){AudioManager.stopBGM();}
else if(msg.type==='sfx-on'){AudioManager.setSfx(true);}
else if(msg.type==='sfx-off'){AudioManager.setSfx(false);}
else if(msg.type==='reset'){StorageManager.resetProgress();AudioManager.stopBGM();AudioManager.setMusic(true);AudioManager.setSfx(true);StorageManager.updateSettings('music',true);StorageManager.updateSettings('sfx',true);AudioManager.startBGM();UIManager.renderMenu();}
else if(msg.type==='close'){UIManager.showMenu();UIManager.renderMenu();if(AudioManager.isMusicOn())AudioManager.startBGM();}});var helloPlayed=false;document.addEventListener('pointerdown',function playHelloAndBGM(){AudioManager.resumeContext();if(!helloPlayed){helloPlayed=true;AudioManager.loadPraiseSprite();AudioManager.playPraise('hello');}
if(AudioManager.isMusicOn())AudioManager.startBGM();},{once:false});UIManager.renderMenu();UIManager.showMenu();UIManager.bindEvents(onLevelClick,onOpenSettings);})();