(function(){var tempAnimalFoods={};function loadData(){var savedFoods=StorageManager.getAnimalFoods();var savedBlocks=StorageManager.getDifficultyBlocks();var settings=StorageManager.getSettings();tempAnimalFoods={};for(var i=0;i<ANIMAL_ORDER.length;i++){var id=ANIMAL_ORDER[i];tempAnimalFoods[id]=(savedFoods&&savedFoods[id])?savedFoods[id].slice():(ANIMAL_FOODS_DEFAULTS[id]||[]).slice();}
tempDiffBlocks=[];var src=(savedBlocks&&savedBlocks.length>0)?savedBlocks:DIFFICULTY_BLOCKS_DEFAULTS;for(var j=0;j<src.length;j++){tempDiffBlocks.push({levelStart:src[j].levelStart,levelEnd:src[j].levelEnd,optionCount:src[j].optionCount,correctCount:src[j].correctCount,targetCount:src[j].targetCount,});}
updateAudioUI(settings.music,settings.sfx);}
function updateAudioUI(musicOn,sfxOn){document.getElementById('music-icon').textContent=musicOn?'🎵':'🔇';document.getElementById('sfx-icon').textContent=sfxOn?'🔊':'🔇';document.getElementById('music-state').textContent=musicOn?'开':'关';document.getElementById('sfx-state').textContent=sfxOn?'开':'关';}
function post(type){window.parent.postMessage({type:type},'*');}
function renderDiffBlocks(){var container=document.getElementById('diff-rows');container.innerHTML='';for(var i=0;i<tempDiffBlocks.length;i++){var b=tempDiffBlocks[i];var row=document.createElement('div');row.className='diff-row';row.innerHTML='<span class="diff-cell">'+b.levelStart+'-'+b.levelEnd+'</span>'+
'<span class="diff-cell"><input type="number" class="diff-input" data-idx="'+i+'" data-field="optionCount" value="'+b.optionCount+'" min="2" max="8"></span>'+
'<span class="diff-cell"><input type="number" class="diff-input" data-idx="'+i+'" data-field="correctCount" value="'+b.correctCount+'" min="1" max="5"></span>'+
'<span class="diff-cell"><input type="number" class="diff-input" data-idx="'+i+'" data-field="targetCount" value="'+b.targetCount+'" min="1" max="10"></span>';container.appendChild(row);}
var inputs=container.querySelectorAll('.diff-input');for(var j=0;j<inputs.length;j++){inputs[j].addEventListener('change',function(){var idx=parseInt(this.getAttribute('data-idx'));var field=this.getAttribute('data-field');var val=parseInt(this.value)||1;if(field==='optionCount')val=Math.max(2,Math.min(8,val));if(field==='correctCount')val=Math.max(1,Math.min(5,val));if(field==='targetCount')val=Math.max(1,Math.min(10,val));tempDiffBlocks[idx][field]=val;this.value=val;});}}
function renderAnimalFoodList(){var container=document.getElementById('animal-food-list');container.innerHTML='';for(var i=0;i<ANIMAL_ORDER.length;i++){var animalId=ANIMAL_ORDER[i];var animal=ANIMALS[animalId];var foods=tempAnimalFoods[animalId]||[];appendAnimalRow(container,animalId,animal,foods);}}
function createAnimalRow(animalId,animal,foods){var row=document.createElement('div');row.className='af-row';row.setAttribute('data-animal',animalId);var label=document.createElement('div');label.className='af-animal';label.innerHTML='<span class="af-emoji">'+animal.emoji+'</span><span class="af-name">'+animal.name+'</span>';var chipsWrap=document.createElement('div');chipsWrap.className='af-chips';for(var j=0;j<foods.length;j++){var food=FOODS[foods[j]];if(!food)continue;var chip=document.createElement('span');chip.className='af-chip';chip.setAttribute('data-food',foods[j]);chip.textContent=food.emoji;chip.title=food.name+'（长按删除）';bindLongPress(chip,animalId,foods[j]);chipsWrap.appendChild(chip);}
var addBtn=document.createElement('button');addBtn.className='af-add-btn';addBtn.textContent='+';addBtn.title='添加食物';addBtn.addEventListener('click',function(){openFoodPicker(animalId);});chipsWrap.appendChild(addBtn);row.appendChild(label);row.appendChild(chipsWrap);return row;}
function appendAnimalRow(container,animalId,animal,foods){container.appendChild(createAnimalRow(animalId,animal,foods));}
function refreshAnimalRow(animalId){var container=document.getElementById('animal-food-list');var oldRow=container.querySelector('.af-row[data-animal="'+animalId+'"]');var animal=ANIMALS[animalId];var foods=tempAnimalFoods[animalId]||[];var newRow=createAnimalRow(animalId,animal,foods);if(oldRow){container.replaceChild(newRow,oldRow);}else{container.appendChild(newRow);}}
function bindLongPress(chip,animalId,foodId){var timer=null;var moved=false;chip.addEventListener('pointerdown',function(){moved=false;timer=setTimeout(function(){if(!moved)removeAnimalFood(animalId,foodId,chip);},600);chip.classList.add('pressing');});chip.addEventListener('pointermove',function(){moved=true;});function cancel(){if(timer){clearTimeout(timer);timer=null;}
chip.classList.remove('pressing');}
chip.addEventListener('pointerup',cancel);chip.addEventListener('pointercancel',cancel);chip.addEventListener('pointerleave',cancel);}
function removeAnimalFood(animalId,foodId,chip){var foods=tempAnimalFoods[animalId];if(foods.length<=1){chip.classList.remove('pressing');showToast('每个动物至少保留1个食物');return;}
var idx=foods.indexOf(foodId);if(idx!==-1)foods.splice(idx,1);chip.classList.add('removing');setTimeout(function(){refreshAnimalRow(animalId);},250);}
var pickerAnimalId=null;function openFoodPicker(animalId){pickerAnimalId=animalId;var animal=ANIMALS[animalId];document.getElementById('picker-animal-name').textContent=animal.emoji+' '+animal.name;var grid=document.getElementById('food-picker-grid');grid.innerHTML='';var currentFoods=tempAnimalFoods[animalId]||[];for(var i=0;i<GAME_CONFIG.ALL_FOOD_IDS.length;i++){var foodId=GAME_CONFIG.ALL_FOOD_IDS[i];var food=FOODS[foodId];var isActive=currentFoods.indexOf(foodId)!==-1;var chip=document.createElement('div');chip.className='picker-chip'+(isActive?' active':'');chip.innerHTML='<span>'+food.emoji+'</span><span class="pick-food-name">'+food.name+'</span><span class="pick-food-en">'+food.en+'</span>';(function(fId,active){chip.addEventListener('click',function(){toggleAnimalFood(pickerAnimalId,fId);});})(foodId,isActive);grid.appendChild(chip);}
document.getElementById('food-picker-overlay').classList.add('active');}
function toggleAnimalFood(animalId,foodId){var foods=tempAnimalFoods[animalId];var idx=foods.indexOf(foodId);if(idx===-1){foods.push(foodId);}else{if(foods.length<=1){showToast('每个动物至少保留1个食物');return;}
foods.splice(idx,1);}
var grid=document.getElementById('food-picker-grid');var chips=grid.querySelectorAll('.picker-chip');var currentFoods=tempAnimalFoods[animalId]||[];for(var i=0;i<chips.length;i++){var fId=GAME_CONFIG.ALL_FOOD_IDS[i];if(fId)chips[i].classList.toggle('active',currentFoods.indexOf(fId)!==-1);}}
function closeFoodPicker(){document.getElementById('food-picker-overlay').classList.remove('active');if(pickerAnimalId)refreshAnimalRow(pickerAnimalId);pickerAnimalId=null;}
function addAnimalFood(animalId,foodId){}
function showToast(msg){var existing=document.querySelector('.toast-msg');if(existing)existing.parentNode.removeChild(existing);var toast=document.createElement('div');toast.className='toast-msg';toast.textContent=msg;document.body.appendChild(toast);setTimeout(function(){toast.classList.add('fade-out');setTimeout(function(){if(toast.parentNode)toast.parentNode.removeChild(toast);},300);},1500);}
function resetDefaults(){loadData();tempAnimalFoods={};for(var i=0;i<ANIMAL_ORDER.length;i++){var id=ANIMAL_ORDER[i];tempAnimalFoods[id]=(ANIMAL_FOODS_DEFAULTS[id]||[]).slice();}
tempDiffBlocks=[];for(var j=0;j<DIFFICULTY_BLOCKS_DEFAULTS.length;j++){var d=DIFFICULTY_BLOCKS_DEFAULTS[j];tempDiffBlocks.push({levelStart:d.levelStart,levelEnd:d.levelEnd,optionCount:d.optionCount,correctCount:d.correctCount,targetCount:d.targetCount,});}
renderDiffBlocks();renderAnimalFoodList();}
function saveSettings(){for(var i=0;i<ANIMAL_ORDER.length;i++){if((tempAnimalFoods[ANIMAL_ORDER[i]]||[]).length===0){showToast('每个动物至少需要1个食物');return;}}
StorageManager.saveAnimalFoods(tempAnimalFoods);StorageManager.saveDifficultyBlocks(tempDiffBlocks);post('close');}
document.getElementById('btn-close').addEventListener('click',function(){post('close');});document.getElementById('btn-save').addEventListener('click',saveSettings);document.getElementById('btn-reset-defaults').addEventListener('click',resetDefaults);document.getElementById('btn-reset').addEventListener('click',function(){document.getElementById('confirm-overlay').classList.add('active');});document.getElementById('btn-confirm-yes').addEventListener('click',function(){document.getElementById('confirm-overlay').classList.remove('active');post('reset');});document.getElementById('btn-confirm-no').addEventListener('click',function(){document.getElementById('confirm-overlay').classList.remove('active');});document.getElementById('btn-music').addEventListener('click',function(){var settings=StorageManager.getSettings();var on=!settings.music;StorageManager.updateSettings('music',on);updateAudioUI(on,settings.sfx);post(on?'music-on':'music-off');});document.getElementById('btn-sfx').addEventListener('click',function(){var settings=StorageManager.getSettings();var on=!settings.sfx;StorageManager.updateSettings('sfx',on);updateAudioUI(settings.music,on);post(on?'sfx-on':'sfx-off');});document.getElementById('btn-picker-close').addEventListener('click',closeFoodPicker);document.getElementById('food-picker-overlay').addEventListener('click',function(e){if(e.target===this)closeFoodPicker();});window.addEventListener('message',function(e){if(e.data&&e.data.type==='open'){loadData();renderDiffBlocks();renderAnimalFoodList();}});loadData();renderDiffBlocks();renderAnimalFoodList();})();